#!/bin/bash
# fedmenu - File Explorer for dmenu

# Config
file_explorer=thunar
terminal_execute="xfce4-terminal -e"
terminal_cd="xfce4-terminal --working-directory"
viewer=xviewer
reader=xreader
mplayer=vlc
vplayer=vlc
office=libreoffice
dmenu_sb="#396535"
dmenu_fn="DejaVu Sans Mono-8"
dmenu_launch="dmenu -sb \"$dmenu_sb\" -fn \"$dmenu_fn\" -i -l 9"

item_open="⮡ Open with ..."
item_back=" Back to directory"
item_open_explorer=" Open in file explorer"
item_open_vim=" Open in Vim"
item_open_xfce4_terminal=" Open in xfce4-terminal"
item_exec=" Execute (bash)"
item_reader=" Open with "$reader
item_viewer=" Open with "$viewer
item_vplayer=" Watch in "$vplayer
item_mplayer=" Play in "$mplayer
item_audacity=" Open in audacity"
item_office=" Open in "$office
item_copypaste=" Copy-paste"
item_selectfile=" Select file"
item_selectdirectory=" Select directory"
item_pastehere=" Paste in here"

# Set CWD to a normalized path if the argument starts with '.' to avoid errors
[[ $1 == .* ]] && CWD=`realpath "$1"` || CWD=$1

# Start from pwd if no file/directory is supplied
if [ -z $1 ];
then
	CWD=$(pwd)
fi

# Modes: normal (explorer), select
mode_normal=explorer
mode_select=select
mode_paste=paste

if [ -z $2 ];
then
	mode=$mode_normal
else
	mode=$2
fi

declare -a items
if [ -d "$CWD" ];
then
	# If item is a directory
	is_directory=true

	case "$mode" in
		$mode_normal)
			# Normal options (directory)

			items+=("$(ls "$CWD" -a)") # All files and directories
			items+=("$item_open_explorer")
			items+=("$item_open_xfce4_terminal")
			items+=("$item_open")
			items+=("$item_copypaste")
			;;
		$mode_select)
			items+=("$(ls "$CWD" -a)") # All files and directories
			items+=("$item_selectdirectory");;
		$mode_paste)
			items+=".."
			items+=("$(find "$CWD/" -maxdepth 1 -mindepth 1 -type d,l -printf "%f\n" | sort)") # Directories only
			items+=("$item_pastehere");;
	esac
else
	# If item is a file

	if [ "$mode" == "$mode_paste" ];
	then
		exec dmenu -p "fedmenu internal error: can not paste into file" -sb "#AA0000"
		exit 1 # ERROR
	fi

	is_file=true
	items+=("$item_open")
	items+=("$item_open_vim")
	[ -x "$CWD" ] && items+=("$item_exec")
	
	case $mode in
		$mode_normal)
			# Normal options (file)
			case "${CWD##*.}" in
				"pdf")
					items+=("$item_reader")
					;;
				"jpg" | "jpeg" | "gif" | "png")
					items+=("$item_viewer")
					;;
				"mp3" | "ogg" | "wav" | "m4a" | "opus")
					items+=("$item_mplayer")
					;;
				"mp4" | "mkv" | "avi")
					items+=("$item_vplayer")
					;;
				"aup")
					items+=("$item_audacity")
					;;
				"odt" | "ods" | "doc" | "docx" | "xls" | "xlsx")
					items+=("$item_office")
					;;
			esac
	
			;;
		$mode_select)
			items+=("$item_selectfile")
			;;
	esac

	# Global options (all modes, file)
	items+=("$item_copypaste")
	items+=("$item_back")
fi

prompt=""
[ -f "$CWD" ] && prompt=""

case $mode in
	$mode_select)
		prompt="Select ${prompt}"
		;;
	$mode_paste)
		prompt="Paste ${prompt}"
		;;
esac

item=$(printf "%s\n" "${items[@]}" | eval "$dmenu_launch -p \"$prompt $CWD\"")

# Exit on Esc
[ -z "$item" ] && exit

# Handle selected option or continue with selected file/directory
case $item in

	$item_back | '..')
		exec fedmenu $(dirname "$CWD") $mode
		;;
	$item_open)
		exec $(compgen -c | eval "$dmenu_launch -p \"Open '$CWD' with\"") "$CWD"
		;;
	$item_open_explorer)
		exec $file_explorer "$CWD"
		;;
	$item_open_vim)
		exec $terminal_execute "vim $CWD"
		;;
	$item_open_xfce4_terminal)
		exec $terminal_cd "$CWD"
		;;
	$item_exec)
		exec "$CWD"
		;;
	$item_reader)
		exec $reader "$CWD"
		;;
	$item_viewer)
		exec $viewer "$CWD"
		;;
	$item_mplayer)
		exec $mplayer "$CWD"
		;;
	$item_vplayer)
		exec $vplayer "$CWD"
		;;
	$item_audacity)
		exec audacity "$CWD"
		;;
	$item_office)
		exec $office "$CWD"
		;;
	$item_copypaste)
		file_name=${CWD##*/}
		location=$(fedmenu "$(pwd)" $mode_paste)

		if [ -z $location ]; # Exit on cancel
		then
			exit
		fi

		if [ -f "${location}/${file_name}" ];
		then
			answer=$(echo -e "No\nYes" | eval "$dmenu_launch -p \"Replace ${location}/${file_name}?\"")
			if [ $answer == "Yes" ];
			then
				exec cp -uR $CWD $location
				exit 0
			fi
			exit 1
		else
			exec cp -R $CWD $location
		fi
		;;
	$item_pastehere)
		echo "$CWD"
		exit 0
		;;
	$item_selectdirectory | $item_selectfile)
		echo "$CWD"
		exit 0
		;;
	'.')
		# Ignore move to current directory
		exec fedmenu "$CWD" "$mode"
		;;
	*)
		# Append item name to the path and continue
		item="$CWD/$item"
		exec fedmenu "$item" "$mode"
		;;
esac

